// Lista de palavras protegida no servidor
const PALAVRAS = [
  "ABACAXI", "ABELHA", "ABÓBORA", "AEROPORTO", "AGULHA", "ALFACE", "ALMOFADA", "AMBULÂNCIA", "ANEL", "ANJO",
  "AQUÁRIO", "ARANHA", "ÁRVORE", "ASA", "ASTRONAUTA", "ATOR", "AVIÃO", "AVÓ", "BACIA", "BALEIA",
  "BALÃO", "BANANA", "BANCO", "BANDEIRA", "BARATA", "BARCO", "BATATA", "BATOM", "BAÚ", "BEBÊ",
  "BERÇO", "BICICLETA", "BIGODE", "BINÓCULO", "BISCOITO", "BOLA", "BOLO", "BOMBA", "BOMBEIRO", "BONÉ",
  "BORBOLETA", "BOTA", "BOTÃO", "BRAÇO", "BRINCO", "BRUXA", "BULE", "BURRO", "CABEÇA", "CABIDE",
  "CACHORRO", "CADEADO", "CADEIRA", "CADERNO", "CAIXA", "CAJU", "CALÇA", "CAMA", "CAMELO", "CAMINHÃO",
  "CAMISA", "CANETA", "CANGURU", "CANOA", "CANTOR", "CAPACETE", "CARACOL", "CARANGUEJO", "CARRO", "CARTA",
  "CASA", "CASTELO", "CAVALO", "CEBOLA", "CELULAR", "CENOURA", "CESTAS", "CHÁ", "CHAVE", "CHINELO",
  "CHOCOLATE", "CHUVA", "CIDADE", "CINTO", "CIRCO", "COBRA", "COELHO", "COFRE", "COLHER", "COMPUTADOR",
  "CONCHA", "COPO", "CORAÇÃO", "COROA", "CORUJA", "COZINHA", "CRAVO", "CRIANÇA", "CROCODILO", "CUBO",
  "DADO", "DEDO", "DENTE", "DESENHO", "DESPERTADOR", "DIAMANTE", "DINHEIRO", "DINOSSAURO", "DISCO", "DOMINÓ",
  "DRAGÃO", "DUCHA", "ELEFANTE", "ELEVADOR", "ENXADA", "ESCADA", "ESCOLA", "ESCOVA", "ESPADA", "ESPELHO",
  "ESQUILO", "ESTÁDIO", "ESTRELA", "FACA", "FADA", "FANTASMA", "FAROL", "FEIJÃO", "FERRADURA", "FLOR",
  "FOCA", "FOGUETE", "FOLHA", "FORMIGA", "FORNO", "FOTO", "FRANGO", "FUTEBOL", "GAIOLA", "GALINHA",
  "GARFO", "GATO", "GAVETA", "GELO", "GELADEIRA", "GIRAFA", "GOLF", "GOLFINHO", "GORILA", "GRAVATA",
  "GUARDA-CHUVA", "GUITARRA", "HAMBÚRGUER", "HARPA", "HELICÓPTERO", "HIPOPÓTAMO", "HOSPITAL", "IGREJA", "IGUANA", "ILHA",
  "ÍMÃ", "ÍNDIO", "INJEÇÃO", "JANELA", "JARRA", "JORNAL", "LÂMPADA", "LÁPIS", "LARANJA", "LEÃO",
  "LEITE", "LIMÃO", "LIVRO", "LIXEIRA", "LOBO", "LOJA", "LUA", "LUVAS", "MAÇÃ", "MACACO",
  "MALA", "MÃO", "MAPA", "MARTELO", "MÁSCARA", "MEIA", "MELANCIA", "MENINA", "MENINO", "MESA",
  "MICROFONE", "MILHO", "MOCHILA", "MOEDA", "MOTO", "MOUSE", "MORANGO", "MÚMIA", "MUNDO", "MÚSICA",
  "NARIZ", "NAVIO", "NEVE", "NINHO", "NOITE", "NOVELO", "NUVEM", "ÓCULOS", "OLHO", "ONÇA",
  "ÔNIBUS", "OVO", "PÁ", "PALHAÇO", "PANELA", "PAPAGAIO", "PARQUE", "PATO", "PAVÃO", "PÉ",
  "PEIXE", "PENA", "PENTE", "PERA", "PERNA", "PIANO", "PINGUIM", "PIPA", "PIRATA", "PIZZA",
  "PLANETA", "POLVO", "POMBA", "PONTE", "PORCO", "PORTA", "PRATO", "PRÉDIO", "PRESENTE", "PROFESSOR",
  "QUEIJO", "RÁDIO", "RAQUETE", "RATO", "RELÓGIO", "REMÉDIO", "RIO", "ROBÔ", "RODA", "ROSA",
  "ROUPA", "SABONETE", "SACOLA", "SAIA", "SAL", "SAPATO", "SAPO", "SERROTE", "SINO", "SOFÁ",
  "SOL", "SORVETE", "TAMBOR", "TAPETE", "TATU", "TELEFONE", "TELEVISÃO", "TÊNIS", "TESOURA", "TIJOLO",
  "TINTA", "TIGRE", "TOMATE", "TORNEIRA", "TORRE", "TORTA", "TREM", "TUBARÃO", "URSO", "UVA",
  "VACA", "VASO", "VELA", "VENTILADOR", "VESTIDO", "VIDRO", "VIOLÃO", "VULCÃO", "XADREZ", "ZEBRA"
];

module.exports = { PALAVRAS };