// Lista de palavras protegida no servidor
const PALAVRAS = [
// --- ANIMAIS ---
  "Abelha", "Abutre", "Água-viva", "Águia", "Alce", "Anta", "Aranha", "Arara", "Avestruz", "Baleia", 
  "Barata", "Besouro", "Bezerro", "Bicho-preguiça", "Bode", "Boi", "Borboleta", "Búfalo", "Burro", 
  "Cabra", "Cachorro", "Camelo", "Camundongo", "Canguru", "Capivara", "Caracol", "Caranguejo", 
  "Carneiro", "Castor", "Cavalo", "Cegonha", "Centopeia", "Chimpanzé", "Cisne", "Coala", "Cobra", 
  "Coelho", "Coiote", "Coruja", "Corvo", "Crocodilo", "Cupim", "Dinossauro", "Doninha", "Dragão", 
  "Dromedário", "Elefante", "Ema", "Esquilo", "Falcão", "Flamingo", "Foca", "Formiga", "Furaão", 
  "Gafanhoto", "Gaivota", "Galinha", "Galo", "Gambá", "Ganso", "Gato", "Gavião", "Girafa", "Golfinho", 
  "Gorila", "Grilo", "Guaxinim", "Hamster", "Hiena", "Hipopótamo", "Iguana", "Jabuti", "Jacaré", 
  "Jaguar", "Javali", "Joaninha", "Lagarta", "Lagartixa", "Lagarto", "Lagosta", "Leão", "Lebre", 
  "Lemure", "Leopardo", "Lhama", "Libélula", "Lince", "Lobo", "Lontra", "Lula", "Macaco", "Mamute", 
  "Marimbondo", "Marreco", "Mico", "Minhoca", "Morcego", "Morsa", "Mosca", "Mosquito", "Mula", 
  "Onça", "Orangotango", "Orca", "Ostra", "Ouriço", "Ovelha", "Panda", "Pantera", "Papagaio", 
  "Pato", "Pavão", "Peixe", "Pelicano", "Perereca", "Peru", "Pinguim", "Piolho", "Piranha", "Polvo", 
  "Pombo", "Ponei", "Porco", "Porco-espinho", "Preguiça", "Pulga", "Puma", "Quati", "Rã", "Raposa", 
  "Rato", "Rinoceronte", "Sapo", "Sardinha", "Serpente", "Siri", "Suricato", "Tamanduá", "Tartaruga", 
  "Tatu", "Texugo", "Tigre", "Toupeira", "Touro", "Tubarão", "Tucano", "Unicórnio", "Urso", "Urubu", 
  "Vaca", "Vagalume", "Veado", "Vespa", "Zebra",

  // --- COMIDA E BEBIDA ---
  "Abacate", "Abacaxi", "Açaí", "Acarajé", "Acelga", "Acerola", "Açúcar", "Agrião", "Aipim", "Alecrim", 
  "Alface", "Alho", "Almôndega", "Amêndoa", "Amendoim", "Amora", "Arroz", "Aveia", "Azeite", "Azeitona", 
  "Bacon", "Banana", "Batata", "Baunilha", "Beirute", "Beterraba", "Bife", "Biscoito", "Bolo", "Bombom", 
  "Brócolis", "Café", "Caju", "Caldo", "Camarão", "Canela", "Canjica", "Caramelo", "Carne", "Cebola", 
  "Cenoura", "Cereal", "Cerveja", "Chá", "Champanhe", "Chantilly", "Chocolate", "Churrasco", "Coco", 
  "Cogumelo", "Cominho", "Cookie", "Costela", "Couve", "Coxinha", "Crepe", "Croissant", "Cupcake", 
  "Damasco", "Doce", "Empada", "Ervilha", "Espaguete", "Espinafre", "Farinha", "Farofa", "Feijão", 
  "Figo", "Filé", "Framboesa", "Frango", "Fruta", "Fubá", "Gelatina", "Geleia", "Gengibre", "Goiaba", 
  "Gorgonzola", "Granola", "Graviola", "Guacamole", "Guaraná", "Hambúrguer", "Hortelã", "Iogurte", 
  "Jabuticaba", "Jaca", "Jantar", "Kiwi", "Laranja", "Lasanha", "Leite", "Lentilha", "Limão", "Linguiça", 
  "Lombo", "Maçã", "Macarrão", "Maionese", "Mamão", "Mandioca", "Manga", "Manteiga", "Maracujá", 
  "Margarina", "Marshmallow", "Mel", "Melancia", "Melão", "Menta", "Milho", "Mirtilo", "Molho", 
  "Morango", "Mortadela", "Mostarda", "Mousse", "Muçarela", "Nabo", "Nachos", "Noz", "Nuggets", "Óleo", 
  "Omelete", "Orégano", "Ovo", "Paçoca", "Palmito", "Pamonha", "Panqueca", "Pão", "Papaya", "Páprica", 
  "Pastel", "Patê", "Pepino", "Pera", "Peru", "Picanha", "Picles", "Pimenta", "Pimentão", "Pipoca", 
  "Pirulito", "Pistache", "Pizza", "Polenta", "Presunto", "Pudim", "Purê", "Queijo", "Quiabo", "Rabanete", 
  "Rapadura", "Ravióli", "Refrigerante", "Repolho", "Requeijão", "Risoto", "Rosquinha", "Rúcula", "Sal", 
  "Salada", "Salame", "Salsão", "Salsicha", "Salsa", "Sanduíche", "Sashimi", "Sorvete", "Sopa", "Suco", 
  "Sushi", "Taco", "Tâmara", "Tangerina", "Tapioca", "Tomate", "Torrada", "Torta", "Torresmo", "Trigo", 
  "Trufa", "Uva", "Vagem", "Vinagre", "Vinho", "Vodka", "Waffle", "Whisky", "Yakiscoba",

  // --- OBJETOS E FERRAMENTAS ---
  "Abajur", "Agulha", "Alfinete", "Algema", "Alicate", "Almofada", "Alto-falante", "Anel", "Antena", 
  "Anzol", "Apagador", "Apito", "Aquário", "Arco", "Armário", "Arquivo", "Aspirador", "Bacia", "Balança", 
  "Balão", "Balde", "Bandeira", "Banheiro", "Banco", "Baralho", "Barco", "Batom", "Bateria", "Baú", 
  "Berço", "Bicicleta", "Binóculo", "Biombo", "Bisturi", "Boia", "Bola", "Boneca", "Boné", "Borracha", 
  "Botão", "Brinco", "Broca", "Bússola", "Cabide", "Cadeado", "Cadeira", "Caderno", "Caixa", "Caixão", 
  "Calculadora", "Calendário", "Cálice", "Câmera", "Camisa", "Caneca", "Caneta", "Canivete", "Cano", 
  "Capacete", "Capa", "Carpete", "Carimbo", "Cartão", "Carteira", "Castelo", "Catapulta", "Celular", 
  "Cesta", "Chave", "Chicote", "Chinelo", "Chupeta", "Cinto", "Cinzeiro", "Clipes", "Cobertor", "Cola", 
  "Colchão", "Colher", "Computador", "Cone", "Controle", "Copo", "Corda", "Coroa", "Cortina", "Coturno", 
  "Crachá", "Cristal", "Cruz", "Dado", "Dardo", "Dentadura", "Despertador", "Diamante", "Diário", "Disco", 
  "Dominó", "Ducha", "Edredom", "Elástico", "Envelope", "Enxada", "Escada", "Escorregador", "Escova", 
  "Escudo", "Espada", "Espelho", "Esponja", "Estátua", "Estojo", "Etiqueta", "Extintor", "Faca", "Facão", 
  "Farol", "Fax", "Fechadura", "Ferro", "Fichário", "Figurinha", "Filmadora", "Fio", "Fita", "Fivela", 
  "Flecha", "Foguete", "Foice", "Folha", "Fone", "Forno", "Fósforo", "Foto", "Frasco", "Freezer", 
  "Frigideira", "Funil", "Furadeira", "Gaiola", "Gaita", "Gancho", "Garfo", "Garrafa", "Gaveta", "Gelo", 
  "Giz", "Globo", "Gorro", "Grampeador", "Gravata", "Guarda-chuva", "Guardanapo", "Guidão", "Guitarra", 
  "Haltere", "Harpa", "Hélice", "Helicóptero", "Hidrante", "Holofote", "Iate", "Ímã", "Impressora", 
  "Ingresso", "Isqueiro", "Jaleco", "Janela", "Jaqueta", "Jarra", "Jornal", "Lã", "Lâmpada", "Lança", 
  "Lancheira", "Lanterna", "Lápis", "Lapiseira", "Lata", "Lençol", "Lenço", "Lente", "Leque", "Livro", 
  "Lixa", "Lixeira", "Lona", "Lousa", "Luva", "Machado", "Maiô", "Mala", "Mamadeira", "Manequim", 
  "Mangueira", "Manivela", "Mapa", "Máquina", "Marreta", "Martelo", "Máscara", "Medalha", "Meia", 
  "Microfone", "Microscópio", "Mochila", "Moeda", "Mola", "Monitor", "Monóculo", "Moto", "Motor", "Mouse", 
  "Navalha", "Nave", "Notebook", "Novelo", "Óculos", "Pá", "Pandeiro", "Panela", "Parafuso", "Paraquedas", 
  "Parede", "Patins", "Patine", "Pedal", "Peneira", "Pente", "Perfume", "Peruca", "Peteca", "Piano", 
  "Pilha", "Pincel", "Pingente", "Pino", "Pinça", "Pipa", "Placa", "Piano", "Pneu", "Ponteiro", "Porta", 
  "Portão", "Pote", "Prancha", "Prato", "Prego", "Presente", "Projetor", "Pulseira", "Puxador", "Quadro", 
  "Quebra-cabeça", "Radar", "Rádio", "Raquete", "Régua", "Relógio", "Remédio", "Remo", "Revista", "Rifle", 
  "Robô", "Roda", "Rodo", "Rolha", "Roupão", "Sabão", "Sabonete", "Saco", "Saia", "Salto", "Sandália", 
  "Sanfona", "Sapatilha", "Sapato", "Satélite", "Saxofone", "Scanner", "Secador", "Sela", "Selo", 
  "Semáforo", "Seringa", "Serra", "Serrote", "Short", "Sino", "Skate", "Sofá", "Sombrinha", "Sonda", 
  "Spray", "Submarino", "Suporte", "Suspensório", "Tábua", "Tabuleta", "Taça", "Tambor", "Tampa", "Tanque", 
  "Tapete", "Teclado", "Tela", "Telefone", "Telescópio", "Televisão", "Telha", "Tênis", "Termômetro", 
  "Tesoura", "Tigela", "Tijolo", "Tinta", "Toalha", "Tocha", "Toldo", "Torneira", "Torre", "Trampolim", 
  "Travesseiro", "Trem", "Triângulo", "Trono", "Tubo", "Turbina", "Uniforme", "Urna", "Vaso", "Vassoura", 
  "Vela", "Ventilador", "Vestido", "Vídeo", "Vidro", "Viola", "Violão", "Violino", "Visor", "Volante", 
  "Xadrez", "Xampu", "Xícara", "Zíper",

  // --- LUGARES E NATUREZA ---
  "Aeroporto", "África", "Aldeia", "América", "Antártida", "Apartamento", "Árvore", "Ásia", "Avenida", 
  "Banco", "Banheiro", "Bar", "Barraca", "Base", "Biblioteca", "Bosque", "Brasil", "Brejo", "Cabana", 
  "Cachoeira", "Cais", "Calçada", "Campo", "Canal", "Canyon", "Capital", "Capela", "Castelo", "Caverna", 
  "Céu", "Chalé", "Chaminé", "Cidade", "Cinema", "Circo", "Clube", "Colégio", "Colina", "Continente", 
  "Consultório", "Cozinha", "Cratera", "Deserto", "Duna", "Edifício", "Escola", "Escritório", "Espaço", 
  "Estação", "Estádio", "Estacionamento", "Estaleiro", "Estrada", "Estufa", "Europa", "Fábrica", 
  "Farmácia", "Farol", "Fazenda", "Feira", "Floresta", "Fonte", "Fortaleza", "Fórum", "Garagem", "Geleira", 
  "Ginásio", "Hospital", "Hotel", "Igreja", "Ilha", "Inferno", "Jardim", "Laboratório", "Lago", "Lagoa", 
  "Livraria", "Loja", "Lua", "Lixão", "Mansão", "Mar", "Marte", "Mercado", "Mina", "Montanha", "Morro", 
  "Museu", "Nuvem", "Oásis", "Oceano", "Olimpo", "Padaria", "País", "Palácio", "Pântano", "Parque", 
  "Passarela", "Pátio", "Piscina", "Planeta", "Planalto", "Pomar", "Ponte", "Porto", "Praça", "Praia", 
  "Prédio", "Prisão", "Quarto", "Quartel", "Rancho", "Refúgio", "Represa", "Restaurante", "Rio", 
  "Rodoviária", "Ruína", "Sala", "Salão", "Selva", "Serra", "Sertão", "Shopping", "Sítio", "Sol", 
  "Sótão", "Supermercado", "Teatro", "Templo", "Terra", "Terraço", "Torre", "Túnel", "Universo", "Vale", 
  "Vulcão", "Zoológico",

  // --- PROFISSÕES E PESSOAS ---
  "Advogado", "Agricultor", "Alfaiate", "Alienígena", "Almirante", "Aluno", "Amigo", "Anão", "Anjo", 
  "Arquiteto", "Artista", "Astronauta", "Atleta", "Ator", "Autor", "Bailarina", "Bancário", "Bandido", 
  "Barbeiro", "Barão", "Bebê", "Bibliotecário", "Biólogo", "Bombeiro", "Bruxa", "Caçador", "Cantor", 
  "Capitão", "Carpinteiro", "Carteiro", "Cientista", "Cigano", "Cirurgião", "Cobrador", "Comandante", 
  "Compositor", "Confeiteiro", "Cozinheiro", "Criança", "Dançarino", "Dentista", "Desenhista", "Detetive", 
  "Diabo", "Diretor", "Doutor", "Duende", "Duque", "Eletricista", "Empregada", "Enfermeira", "Engenheiro", 
  "Escritor", "Escoteiro", "Espião", "Estudante", "Fada", "Fantasma", "Fazendeiro", "Feiticeiro", 
  "Filósofo", "Florista", "Fotógrafo", "Freira", "Garçonete", "Gari", "General", "Gênio", "Gigante", 
  "Ginasta", "Governador", "Guarda", "Guerreiro", "Herói", "Homem", "Imperador", "Índio", "Inimigo", 
  "Inspetor", "Jardineiro", "Jogador", "Jornalista", "Juiz", "Ladrão", "Lobisomem", "Mágico", "Maestro", 
  "Mãe", "Marinheiro", "Mecânico", "Médico", "Mendigo", "Mergulhador", "Mestre", "Militar", "Mineiro", 
  "Modelo", "Monge", "Monstro", "Mordomo", "Motorista", "Mulher", "Múmia", "Músico", "Ninja", "Noiva", 
  "Padre", "Pai", "Palhaço", "Papa", "Papai Noel", "Pastor", "Pato Donald", "Pedreiro", "Pescador", 
  "Piloto", "Pintor", "Pirata", "Político", "Policial", "Porteiro", "Presidente", "Professor", 
  "Psicólogo", "Rainha", "Rei", "Repórter", "Robô", "Sacerdote", "Samurai", "Secretária", "Segurança", 
  "Soldado", "Super-herói", "Taxista", "Técnico", "Vampiro", "Vendedor", "Veterinário", "Vigilante", 
  "Viking", "Vizinho", "Zumbi",

  // --- CORPO E VESTUÁRIO (que não são objetos) ---
  "Alma", "Barba", "Bigode", "Boca", "Braço", "Cabeça", "Cabelo", "Calcanhar", "Canela", "Cara", 
  "Cérebro", "Cílios", "Cintura", "Coluna", "Coração", "Corpo", "Costas", "Cotovelo", "Crânio", "Dedo", 
  "Dente", "Esqueleto", "Estômago", "Face", "Fígado", "Garganta", "Joelho", "Lábio", "Língua", "Mão", 
  "Mente", "Nariz", "Olho", "Ombro", "Orelha", "Osso", "Pé", "Peito", "Pele", "Perna", "Pescoço", 
  "Pulmão", "Pulso", "Queixo", "Rim", "Rosto", "Sangue", "Sobrancelha", "Testa", "Tronco", "Unha", 
  "Veia", "Ventre"
];
module.exports = { PALAVRAS };